name: dotnet build
on:
    push:
        branches:
            - develop
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Setup .NET sdk
              uses: actions/setup-dotnet@v5
              with:
                  dotnet-version: |
                      9.0.x
            - name: Checkout
              uses: actions/checkout@v5
            - name: Build .NET
              run: dotnet build --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj
            - name: Test
              run: dotnet test src/Tests/Nop.Tests/Nop.Tests.csproj
            - name: Publish .NET Package
              run: dotnet publish --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj -o published/