name: dotnet build
on:
    push:
        branches:
            - develop
    workflow_dispatch:
jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v5
            - name: Cache NuGet packages
              uses: actions/cache@v4
              with:
                  path: ~/.nuget/packages
                  key: ${{ runner.os }}-nuget-${{ hashFiles('**/*.csproj') }}
                  restore-keys: |
                      ${{ runner.os }}-nuget-
            - name: Build .NET
              run: dotnet build --configuration Release src/Presentation/Nop.Web/Nop.Web.csproj --no-restore
            - name: Test
              run: dotnet test --logger "trx;LogFileName=test-results.trx" src/Tests/Nop.Tests/Nop.Tests.csproj --results-directory ./TestResults
            
